# Generated by Django 6.0.4 on 2026-05-09 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(blank=True, max_length=200)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('submitted_date', models.DateField(blank=True, null=True)),
                ('cleared_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted to Provider'), ('clear', 'Clear'), ('flagged', 'Flagged'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='compliance/background_checks/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'background_checks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Data Export'), ('approve', 'Approve'), ('reject', 'Reject'), ('view', 'View'), ('other', 'Other')], max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(blank=True, max_length=50)),
                ('object_repr', models.CharField(blank=True, max_length=300)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='audit_logs_model_n_656046_idx'), models.Index(fields=['user', 'timestamp'], name='audit_logs_user_id_88267f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('wwcc', 'Working With Children Check'), ('first_aid', 'First Aid Certificate'), ('coaching_license', 'Coaching License'), ('police_check', 'Police Background Check'), ('medical_clearance', 'Medical Clearance'), ('insurance', 'Insurance'), ('safeguarding', 'Safeguarding Training'), ('other', 'Other')], max_length=30)),
                ('document_number', models.CharField(blank=True, max_length=100)),
                ('issuing_body', models.CharField(blank=True, max_length=200)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='compliance/documents/')),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('expiring', 'Expiring Soon'), ('expired', 'Expired'), ('pending', 'Pending Review'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='athletes.athlete')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_compliance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'compliance_records',
                'ordering': ['expiry_date'],
                'indexes': [models.Index(fields=['status', 'expiry_date'], name='compliance__status_34058b_idx'), models.Index(fields=['record_type'], name='compliance__record__ba3b93_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('injury', 'Injury'), ('near_miss', 'Near Miss'), ('safeguarding', 'Safeguarding Concern'), ('property', 'Property Damage'), ('behavioural', 'Behavioural'), ('other', 'Other')], default='injury', max_length=30)),
                ('severity', models.CharField(choices=[('low', 'Low — Minor, no medical attention needed'), ('medium', 'Medium — First aid administered'), ('high', 'High — Medical / hospital required'), ('critical', 'Critical — Life threatening / emergency')], default='low', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('under_review', 'Under Review'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('incident_date', models.DateTimeField()),
                ('location', models.CharField(blank=True, max_length=300)),
                ('witnesses', models.TextField(blank=True)),
                ('description', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('escalated_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_incidents', to=settings.AUTH_USER_MODEL)),
                ('involved_athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incident_reports', to='athletes.athlete')),
                ('involved_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='involved_incidents', to=settings.AUTH_USER_MODEL)),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'incident_reports',
                'ordering': ['-incident_date'],
                'indexes': [models.Index(fields=['status', 'severity'], name='incident_re_status_97c48d_idx'), models.Index(fields=['incident_date'], name='incident_re_inciden_6db0bc_idx')],
            },
        ),
    ]
