# Generated by Django 6.0.4 on 2026-05-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('metric_name', models.CharField(choices=[('registrations_total', 'Total Registrations'), ('registrations_by_team', 'Registrations by Team'), ('registrations_by_age', 'Registrations by Age Group'), ('revenue_collected', 'Revenue Collected'), ('revenue_pending', 'Revenue Pending'), ('revenue_overdue', 'Revenue Overdue'), ('collection_rate', 'Collection Rate %'), ('athletes_active', 'Active Athletes'), ('athletes_by_team', 'Athletes by Team'), ('attendance_rate', 'Training Attendance Rate %'), ('compliance_valid', 'Compliance Records Valid'), ('compliance_expiring', 'Compliance Records Expiring'), ('compliance_expired', 'Compliance Records Expired'), ('incidents_open', 'Open Incidents'), ('transfers_pending', 'Pending Transfers')], max_length=60)),
                ('dimension', models.CharField(blank=True, default='', max_length=100)),
                ('value', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('breakdown', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_snapshots',
                'ordering': ['-date', 'metric_name'],
                'indexes': [models.Index(fields=['metric_name', 'date'], name='analytics_s_metric__62a5b6_idx')],
                'unique_together': {('date', 'metric_name', 'dimension')},
            },
        ),
    ]
