# Generated by Django 6.0.4 on 2026-05-09 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9, unique=True)),
                ('registration_open_date', models.DateField()),
                ('registration_close_date', models.DateField()),
                ('standard_fee', models.DecimalField(decimal_places=2, default=185.0, max_digits=10)),
                ('sibling_discount_fee', models.DecimalField(decimal_places=2, default=155.0, max_digits=10)),
                ('scholarship_slots', models.IntegerField(default=20)),
                ('scholarship_slots_used', models.IntegerField(default=0)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('early_bird_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('late_fee', models.DecimalField(decimal_places=2, default=25.0, max_digits=10)),
                ('require_waiver', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'season_configs',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_tier', models.CharField(choices=[('standard', 'Standard'), ('sibling', 'Sibling Discount'), ('scholarship', 'Scholarship'), ('early_bird', 'Early Bird')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('refunded', 'Refunded'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('stripe', 'Stripe'), ('cash', 'Cash'), ('check', 'Check'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateField()),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='athletes.athlete')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.seasonconfig')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_via', models.CharField(max_length=20)),
                ('status', models.CharField(default='sent', max_length=20)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.payment')),
            ],
            options={
                'db_table': 'payment_reminders',
            },
        ),
        migrations.CreateModel(
            name='StripeTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='usd', max_length=3)),
                ('status', models.CharField(max_length=50)),
                ('receipt_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.payment')),
            ],
            options={
                'db_table': 'stripe_transactions',
            },
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'due_date'], name='payments_status_422e56_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['athlete', 'season'], name='payments_athlete_b7470b_idx'),
        ),
    ]
