# Generated by Django 6.0.4 on 2026-05-08 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Summer Season', max_length=100)),
                ('season', models.CharField(max_length=20)),
                ('fee', models.DecimalField(decimal_places=2, default=450.0, max_digits=8)),
                ('early_bird_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('early_bird_deadline', models.DateField(blank=True, null=True)),
                ('registration_open', models.DateField()),
                ('registration_close', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-registration_open'],
            },
        ),
        migrations.CreateModel(
            name='HQRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_first_name', models.CharField(max_length=100)),
                ('athlete_last_name', models.CharField(max_length=100)),
                ('athlete_dob', models.DateField()),
                ('athlete_gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('P', 'Prefer not to say')], max_length=2)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=10)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relationship', models.CharField(blank=True, max_length=100)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('medical_notes', models.TextField(blank=True)),
                ('has_allergies', models.BooleanField(default=False)),
                ('allergies', models.CharField(blank=True, max_length=200)),
                ('waiver_accepted', models.BooleanField(default=False)),
                ('photo_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hq_registrations', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hq.seasonprogram')),
            ],
        ),
    ]
