# Generated by Django 6.0.4 on 2026-05-09 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hqregistration',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hqregistration',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('pending', 'Payment Pending'), ('paid', 'Paid')], default='unpaid', max_length=20),
        ),
        migrations.AddField(
            model_name='hqregistration',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
