# Generated by Django 5.1.4 on 2025-01-10 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('athlete_name', models.CharField(max_length=100)),
                ('athlete_mark', models.IntegerField(max_length=15)),
                ('athlete_age', models.IntegerField(max_length=2)),
                ('athlete_group', models.CharField(max_length=10)),
                ('athlete_date', models.IntegerField(max_length=4)),
                ('athlete_meet', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Athelete Records',
            },
        ),
    ]
