# Generated by Django 5.1.4 on 2025-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athlete_records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athleterecords',
            name='athlete_class',
            field=models.CharField(choices=[('40 Yard Dash', '40 Yard Dash'), ('50 Yard Dash', '50 Yard Dash'), ('100 Meters', '100 Meters'), ('200 Meters', '200 Meters'), ('400 Meters', '400 Meters'), ('800 Meters', '800 Meters'), ('1500 Meters', '1500 Meters'), ('3000 Meters', '3000 Meters'), ('80m Hurdles -39 inches', '80m Hurdles -39 inches'), ('80m Hurdles -30 inches', '80m Hurdles -30 inches'), ('80m Hurdles -33 inches', '80m Hurdles -33 inches'), ('100m Hurdles - 39 inches', '100m Hurdles - 39 inches'), ('100m Hurdles - 33 inches', '100m Hurdles - 33 inches'), ('100m Hurdles - 30 inches', '100m Hurdles - 30 inches'), ('110m Hurdles - 39 inches', '110m Hurdles - 39 inches'), ('110m Hurdles - 42 inches', '110m Hurdles - 42 inches'), ('200m Hurdles - 36 inches', '200m Hurdles - 36 inches'), ('200m Hurdles - 30 inches', '200m Hurdles - 30 inches'), ('400m Hurdles - 36 inches', '400m Hurdles - 36 inches'), ('2k Steeplechase - 838mm', '2k Steeplechase - 838mm'), ('4x100 Relay', '4x100 Relay'), ('4x400 Relay', '4x400 Relay'), ('4x800 Relay', '4x800 Relay'), ('Shot Put - 12lb', 'Shot Put - 12lb'), ('Shot Put - 2kg', 'Shot Put - 2kg'), ('Shot Put - 6lb', 'Shot Put - 6lb'), ('Shot Put - 8lb', 'Shot Put - 8lb'), ('Shot Put - 4kg', 'Shot Put - 4kg'), ('Shot Put - 16lb', 'Shot Put - 16lb'), ('Discuss - 1.6kg', 'Discuss - 1.6kg'), ('Discuss - 1kg', 'Discuss - 1kg'), ('Javelin - 800g', 'Javelin - 800g'), ('Javelin - 300g TJ', 'Javelin - 300g TJ'), ('Javelin - 300g', 'Javelin - 300g'), ('Javelin - 450g AeroJav', 'Javelin - 450g AeroJav'), ('Javelin - 600g', 'Javelin - 600g'), ('High Jump', 'High Jump'), ('Pole Vault', 'Pole Vault'), ('Long Jump', 'Long Jump'), ('Triple Jump', 'Triple Jump'), ('Hammer', 'Hammer'), ('Triathlon - standard', 'Triathlon - standard'), ('Pentathlon (outdoor)- Standard', 'Pentathlon (outdoor)- Standard'), ('Decathlon - Standard', 'Decathlon - Standard')], default='select class', max_length=50),
        ),
        migrations.AlterField(
            model_name='athleterecords',
            name='athlete_age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='athleterecords',
            name='athlete_date',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='athleterecords',
            name='athlete_mark',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
    ]
