# Generated by Django 6.0.4 on 2026-05-09 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('import_type', models.CharField(default='generic', max_length=50)),
                ('total_records', models.IntegerField()),
                ('successful_records', models.IntegerField()),
                ('failed_records', models.IntegerField()),
                ('errors', models.JSONField(default=list)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'bulk_import_logs',
            },
        ),
        migrations.CreateModel(
            name='RegistrationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=100)),
                ('entry_number', models.CharField(blank=True, max_length=100)),
                ('sportsengine_id', models.CharField(blank=True, max_length=100)),
                ('account_email', models.EmailField(blank=True, max_length=254)),
                ('order_status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('pending', 'Pending')], default='active', max_length=20)),
                ('entry_status', models.CharField(blank=True, max_length=50)),
                ('unclaimed_profiles', models.CharField(blank=True, max_length=100)),
                ('sport', models.CharField(blank=True, max_length=100)),
                ('registration_type', models.CharField(blank=True, max_length=100)),
                ('registrant_type', models.CharField(blank=True, max_length=100)),
                ('volunteer_willing', models.BooleanField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('gross_outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('service_fee_outstanding', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discount_names', models.CharField(blank=True, max_length=500)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('refunds', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('credits', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('registration_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_orders', to='athletes.athlete')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.seasonconfig')),
            ],
            options={
                'db_table': 'registration_orders',
                'ordering': ['-registration_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_data', models.JSONField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='athletes.athlete')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.seasonconfig')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'registration_submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Waiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='waivers/%Y/%m/')),
                ('signed_by_name', models.CharField(blank=True, max_length=200)),
                ('signed_by_relationship', models.CharField(blank=True, max_length=100)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waivers', to='athletes.athlete')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.seasonconfig')),
            ],
            options={
                'db_table': 'waivers',
                'ordering': ['-signed_at'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationFormConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('field_label', models.CharField(max_length=200)),
                ('field_type', models.CharField(max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('is_enabled', models.BooleanField(default=True)),
                ('options', models.JSONField(blank=True, default=list)),
                ('order', models.IntegerField(default=0)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_configs', to='finance.seasonconfig')),
            ],
            options={
                'db_table': 'registration_form_configs',
                'ordering': ['order'],
                'unique_together': {('season', 'field_name')},
            },
        ),
    ]
