# Generated by Django 6.0.4 on 2026-05-09 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AthleteDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('birth_cert', 'Birth Certificate'), ('waiver', 'Waiver Form'), ('medical', 'Medical Clearance'), ('photo_release', 'Photo Release'), ('report_card', 'Report Card')], max_length=20)),
                ('file', models.FileField(upload_to='athlete_docs/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'athlete_documents',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('relationship', models.CharField(blank=True, max_length=100)),
                ('home_phone', models.CharField(blank=True, max_length=30)),
                ('work_phone', models.CharField(blank=True, max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'emergency_contacts',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('cell_phone', models.CharField(blank=True, max_length=30)),
                ('home_phone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'db_table': 'guardians',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('P', 'Prefer not to say')], max_length=2)),
                ('jersey_size', models.CharField(blank=True, choices=[('YXS', 'Youth XS'), ('YS', 'Youth S'), ('YM', 'Youth M'), ('YL', 'Youth L'), ('YXL', 'Youth XL'), ('S', 'Adult S'), ('M', 'Adult M'), ('L', 'Adult L'), ('XL', 'Adult XL'), ('XXL', 'Adult XXL')], max_length=4)),
                ('jersey_number', models.IntegerField(blank=True, null=True)),
                ('tank_size', models.CharField(blank=True, max_length=30)),
                ('shorts_size', models.CharField(blank=True, max_length=30)),
                ('street_address_1', models.CharField(blank=True, max_length=200)),
                ('street_address_2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='United States', max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact_relationship', models.CharField(blank=True, max_length=50)),
                ('secondary_contact_phone', models.CharField(blank=True, max_length=20)),
                ('medical_notes', models.TextField(blank=True)),
                ('medications', models.TextField(blank=True)),
                ('has_allergies', models.BooleanField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True)),
                ('allergy_1', models.CharField(blank=True, max_length=200)),
                ('allergy_2', models.CharField(blank=True, max_length=200)),
                ('allergy_3', models.CharField(blank=True, max_length=200)),
                ('allergy_4', models.CharField(blank=True, max_length=200)),
                ('has_medical_conditions', models.BooleanField(blank=True, null=True)),
                ('medical_condition_1', models.CharField(blank=True, max_length=200)),
                ('medical_condition_2', models.CharField(blank=True, max_length=200)),
                ('medical_condition_3', models.CharField(blank=True, max_length=200)),
                ('medical_condition_4', models.CharField(blank=True, max_length=200)),
                ('physician_name', models.CharField(blank=True, max_length=200)),
                ('physician_first_name', models.CharField(blank=True, max_length=100)),
                ('physician_last_name', models.CharField(blank=True, max_length=100)),
                ('physician_phone', models.CharField(blank=True, max_length=20)),
                ('physician_phone_2', models.CharField(blank=True, max_length=20)),
                ('hospital_of_choice', models.CharField(blank=True, max_length=200)),
                ('insurance_provider', models.CharField(blank=True, max_length=100)),
                ('insurance_group_number', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_number', models.CharField(blank=True, max_length=100)),
                ('insurance_policy_holder', models.CharField(blank=True, max_length=200)),
                ('insurance_phone', models.CharField(blank=True, max_length=20)),
                ('secondary_email', models.EmailField(blank=True, max_length=254)),
                ('volunteer_willing', models.BooleanField(blank=True, null=True)),
                ('sportsengine_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('player_profile_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('graduated', 'Graduated')], default='active', max_length=20)),
                ('waiver_signed', models.BooleanField(default=False)),
                ('waiver_signed_date', models.DateField(blank=True, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='athletes/')),
                ('primary_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_athletes', to=settings.AUTH_USER_MODEL)),
                ('secondary_contacts', models.ManyToManyField(blank=True, related_name='secondary_athletes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'athletes',
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
