# Generated by Django 6.0.4 on 2026-05-09 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('athletes', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='athletes', to='teams.team'),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='athletes.athlete'),
        ),
        migrations.AddField(
            model_name='athletedocument',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='athletes.athlete'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='athletes.athlete'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['team', 'status'], name='athletes_team_id_edf4b1_idx'),
        ),
        migrations.AddIndex(
            model_name='athlete',
            index=models.Index(fields=['last_name', 'first_name'], name='athletes_last_na_c69a51_idx'),
        ),
    ]
